#!/bin/sh

PATH=/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin

for table in "conntrack" "mangle" "nat" "filter" "IMQ" ; do
  while read rt; do
    if [ "$table" = "$rt" ]; then
      iptables-save -t $table | case $1 in
        '-r') 
          sed -r "s/^(\:[A-Za-z0-9\_\-]+ (ACCEPT|DROP|-) \[)[[:digit:]]+\:[[:digit:]]+\]/\10:0\]/" 
          ;;
        *) 
          cat - 
          ;;
      esac
    fi
  done < /proc/net/ip_tables_names
done
