#!/bin/sh
exit 0
PREREQ="mdadm"

prereqs()
{
  echo "$PREREQ"
}

case "$1" in
  prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

test -n "${DESTDIR}" && test -w "${DESTDIR}/etc/mdadm/mdadm.conf" && /sbin/mdadm --detail --scan > "${DESTDIR}/etc/mdadm/mdadm.conf"
