#!/bin/sh
### list-commands
##+     - List available commands

find "$HOME/git-shell-commands" -xdev -mindepth 1 -maxdepth 1 -type f -execdir grep -E '^##[+#] (.+)$' "{}" \; | sed -Ee 's/^##[+#] //;'
